# Configurations
title:            Enso Developer Documentation
longtitle:        Enso Developer Documentation
author:           Enso.org
email:            contact@enso.org
description: >
  The developer documentation for the Enso compiler, runtime, and IDE..

version:          1.0
gitbook_version:  3.2.3

url:              'https://dev.enso.org'
baseurl:          ''
rss:              RSS

# markdown render engine.
markdown:         kramdown
kramdown:
  auto_ids:               true
  input:                  GFM
  math_engine:            mathjax
  smart_quotes:           lsquo,rsquo,ldquo,rdquo
  toc_levels:             1..6
  syntax_highlighter:     rouge
  syntax_highlighter_opts:
    guess_lang:           true

markdown_ext:     markdown,mkdown,mkdn,mkd,md

# Readme Index
readme_index:
  remove_originals: true
  with_frontmatter: true

# Permalinks
permalink:        /:categories/:year-:month-:day-:title:output_ext

exclude:
  - _drafts
  - _submodules

destination:      ./_site
incremental:      false
regenerate:       true

plugins:
  - jemoji
  - jekyll-readme-index
